language: node_js

node_js:
- '0.12'

branches:
  only:
  - source

before_install:
- npm install -g hexo-cli

install:
- npm install

script:
- git submodule init
- git submodule update
- hexo generate

after_success:
- git config --global user.name "Mark Wallace"
- git config --global user.email "lotabout@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy

env:
  global:
    secure: QAH+/EIDC/JgvfahG1FLoNertiaCeuRnqG7tVnZkkjUhdM3BNgSZWOvEtt+bFc+BQP+CMP6hupcnV4rMMmc3trUNxJ2Z2VCnQ8pv5N9LGJ9BVu/93532Ot5KKf8/WewoNFFA/ss6MP4UdHHic64EEifrVi4iOXM6XX3YCwxirBd0mJIp+2fJcusQK42AVMRNmGj/7+B0oNfxMJCOx6to58VZjgFXUWROVsRRQ3pKPVpux7eL7z2YSIXCAe1/ozCTs0Oq858nPtV0peku5DjVLDKeneQQTjm4GnnVmTcyotlixJX+276F0DC4d/fYGUSGy0uQ8LhAWSFhOWLLEAgl6X1Jyh1TGXAsmp33ftSCnZHVaPQVtHENcWLDSJuNuhYTeG3I/PCTEyS6YJ0NSPb3D8w2zOUYIFjrTD8QnPgJB6JNeuMcDDgn8M7/PtWPZZnwvDuzsRNw8pUrx9JI2R8q26QBHUtuGCSETueVAowAR53WKanRt6NMPU5PU5Ofm77+/67RR3z3EAwZS2fGceetIIrfHKlU1Mfroj+FijzjJcIGUriqpVbm+oZwGV3SCEqJLafYRkhKaEL8nFIM02ozohfSaMs50+kBXqG8wDwpmVq9UR6c/RPE9/oafAAkXO00+TT1xhhK45dJYMSYVyd7mnUuOKf0Vv4nzOrOmlbCPxE=
